# Generated by Django 3.2.8 on 2022-04-10 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mgdata',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('father', models.CharField(max_length=50)),
                ('phone', models.BigIntegerField()),
                ('disease', models.CharField(max_length=100)),
                ('desc', models.TextField(default='', null=True)),
            ],
        ),
    ]
