# Generated by Django 3.2.8 on 2022-04-10 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgsystem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mguser',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('uname', models.CharField(max_length=50)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Mguser',
                'verbose_name_plural': 'Mgusers',
            },
        ),
    ]
