# Generated by Django 3.2.8 on 2022-04-10 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mgsystem', '0003_mgdata_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mgdata',
            old_name='id',
            new_name='sno',
        ),
    ]
