# Generated by Django 3.2.8 on 2022-04-11 19:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mgsystem', '0006_auto_20220412_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='mgdata',
            name='jiontime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
