# Generated by Django 3.2.8 on 2022-04-11 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgsystem', '0007_mgdata_jiontime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mgdata',
            name='img',
            field=models.ImageField(upload_to='studentsimg'),
        ),
        migrations.AlterField(
            model_name='mgdata',
            name='jiontime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='mgdata',
            name='section',
            field=models.CharField(default='A', max_length=3, null=True),
        ),
    ]
