# Generated by Django 3.2.8 on 2022-04-12 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgsystem', '0008_auto_20220412_0452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mgdata',
            name='section',
            field=models.CharField(default='A', max_length=3),
        ),
    ]
